core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="main"),
    # path("index-test", views.landing_test, name="landing-test"),
    path("policy/disclaimer", views.disclaimer, name="disclaimer"),
    path("policy/personal-info", views.personal_info_usage, name="personal-info"),
    path("popup-callback", views.PopupCallback.as_view(), name="popup_callback"),
    path("completed_alert", views.CompletedAlert.as_view(), name="completed_alert"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("download/<str:filepath>/", views.download_file),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views, cron


app_name = "orders"

urlpatterns = [
    path("orderingCart/", views.orderingCart, name="ordering_cart"),
    path("payment/update/<int:pk>/", views.payment_update, name="payment_update"),
    path("payment/", views.payment_create, name="payment_create"),
    path("payment/change-address", views.changeAddressAjax, name="payment_change-address"),
    # path('payment/success', views.payment_success, name="payment_success"),
    path("payment/fail", views.payment_fail, name="payment_fail"),
    path("payment/valid", views.payment_valid, name="payment_valid"),
    path("payment/vbank-progress", views.vbank_progess, name="vbank_progess"),
    path("payment/vbank-deposit", views.vbank_deposit, name="vbank_deposit"),
    path(
        "payment/vbank-template-test",
        views.vbank_template_test,
        name="vbank_template_test",
    ),
    path("payment/cancel/<int:pk>", views.order_cancel, name="payment_cancel"),
    # path('payment_fail', views.fail_test, name="fail_test"), 결제취소 창 테스트용 path
    path("change-refund/<int:pk>", views.create_change_or_refund, name="change_refund"),
    path("payment/subscribe", views.sub_modal, name="payment_success_modal"),
    path("payment/gift", views.payment_create_gift, name="payment_gift"),
    path("payment/gift/update", views.payment_update_gift, name="payment_gift_update"),
    path("payment/gift/valid", views.payment_valid_gift, name="payment_gift_valid"),
    path(
        "payment/gift/popup/address",
        views.delivery_address_update,
        name="payment_gift_delivery_update",
    ),
    path(
        "payment/gift/popup/order",
        views.payment_gift_order_list_popup,
        name="payment_gift_order_list",
    ),
    path(
        "payment/calculate-delivery-fee",
        views.calculate_delivery_fee,
        name="calculate_delivery_fee",
    ),
    # crontab actions
    path("cron/delete-pendings", cron.delete_waiting_orders, name="delete_pending_orders"),
    # temp test
    path("kafka", views.tmp, name="kafka_test"),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("list/", views.StoreList.as_view(), name="store_list"),
    path("list/<slug:cat>/", views.store_list_cat, name="store_list_category"),
    path("detail/<int:pk>/", views.product_detail, name="product_detail"),
    path("detail/qna_paginator/", views.question_paging, name="qna_paginator"),
    # path('enroll/', views.product_enroll, name="product_enroll"),
    # path('delete/<int:pk>/', views.product_delete, name="product_delete"),
    # path('update/<int:pk>/', views.product_update, name="product_update"),
    path("question/create", views.create_question, name="question_create"),
    path("question/<int:pk>", views.read_qna, name="question_read"),
    # pagination
    path("detail/<int:pk>/comment_ajax/", views.comment_ajax, name="comment_ajax"),
    path("detail/<int:pk>/question_ajax/", views.question_ajax, name="question_ajax"),
    # EP
    path("get-db", views.get_product_EP, name="get_product_db"),
    path("get-db/daum", views.get_product_daum_EP, name="get_product_db_daum"),

]

users/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_login_callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("signup_kakao", views.SocialSignup.as_view(), name="kakao_signup"),
    path(
        "signup/terms_of_service",
        views.terms_of_service_popup,
        name="signup_terms_of_service",
    ),
    path("signup/personal_info", views.personal_info_popup, name="signup_personal_info"),
    path("signup/id_validation/", views.idValidation, name="id_validation"),
    path(
        "signup/nickname_validation/",
        views.nicknameValidation,
        name="nickname_validation",
    ),
    path("signup/email_validation/", views.emailValidation, name="email_validation"),
    path(
        "signup/phone_number_validation/",
        views.phoneNumberValidation,
        name="phone_number_validation",
    ),
    path(
        "signup/phone_number_authentication/",
        views.phoneNumberAuthentication,
        name="phone_number_authentication",
    ),
    path("password_reset/", views.MyPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.MyPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.MyPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.MyPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("mypage/<slug:cat>", views.mypage, name="mypage"),
    path("editor_mypage/", views.EditorMyPage.as_view(), name="editor_mypage"),
    path(
        "editor_mypage/comments",
        views.EditorMyPage_Comments.as_view(),
        name="editor_mypage_comments",
    ),
    path(
        "editor_mypage/info",
        views.EditorMypage_Info.as_view(),
        name="editor_mypage_info",
    ),
    path("find_my_id/", views.FindMyIdView.as_view(), name="find_my_id"),
    path("find_my_id/complete", views.FindMyIdView.as_view(), name="find_my_id_complete"),
    path("find_my_id/failed", views.FindMyIdFailView.as_view(), name="find_my_id_failed"),
    path("cartIn/", views.CartInAjax, name="cartInAjax"),
    path("cartOut/", views.cartOutAjax, name="cartOutAjax"),
    path("subs/", views.subs, name="subs"),
    path("cancelSubs/", views.cancelSubs, name="cancelSubs"),
    path("wish/", views.wish, name="wish"),
    path("cancelWish/", views.cancelWish, name="cancelWish"),
    path("infoUpdate/", views.infoUpdate, name="infoUpdate"),
    path("profileUpdate/", views.profileUpdate, name="profileUpdate"),
    path("default-address", views.set_default_address_ajax, name="set_default_address_ajax"),
    path("test/", views.testview, name="testview"),
    path("product_refund_test/", views.product_refund, name="product_refund"),
    path("landing_test/", views.landing_test, name="landing_test"),
    # mypage popups
    path(
        "mypage/orders/<int:orderpk>/review/create",
        views.ProductCommentCreate.as_view(),
        name="product_comment_create",
    ),
    path(
        "mypage/orders/<int:grouppk>",
        views.vbank_account_confirm,
        name="vbank_account_confirm",
    ),
    path(
        "mypage/orders/review/<int:reviewpk>",
        views.productCommentDetail.as_view(),
        name="product_comment_detail",
    ),
    path("mypage/orders/list", views.OrderListPopup.as_view(), name="order_list_popup"),
    path("mypage/orders/shipping-info/<int:pk>", views.mypage_shipping_info_popup, name="mypage_shipping_info_popup"),
    # mypage pagination ajax
    path("mypage/orders-ajax/", views.mypage_orders_ajax, name="mypage_orders_ajax"),
]

users/forms.py
from django import forms
from . import models
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.contrib.auth.password_validation import validate_password
from django.forms.widgets import NumberInput
from django.contrib.auth.forms import PasswordResetForm
from django.templatetags.static import static
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class LoginForm(forms.Form):
    username = forms.CharField(
        label="아이디",
        max_length=100,
        widget=forms.TextInput(attrs={"placeholder": "아이디를 입력해주세요"}),
    )
    password = forms.CharField(
        label="비밀번호", widget=forms.PasswordInput(attrs={"placeholder": "비밀번호를 입력해주세요"})
    )

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = models.User.objects.get(username=username)
            if user.check_password(password):
                return self.cleaned_data
            else:
                raise models.User.DoesNotExist
        except models.User.DoesNotExist:
            raise ValidationError("가입하지 않은 ID거나 비밀번호가 틀렸습니다.")


GENDER_CHOICES = {
    ("male", "남성"),
    ("female", "여성"),
}


class SignUpForm(forms.Form):
    username = forms.CharField(
        label="아이디",
        max_length=100,
        label_suffix="",
        widget=forms.TextInput(attrs={"placeholder": "6자 이상의 영문 혹은 영문과 숫자를 조합"}),
    )
    password = forms.CharField(
        label="비밀번호",
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호를 입력하세요"}),
        label_suffix="",
    )
    password_re = forms.CharField(
        label="비밀번호 확인",
        widget=forms.PasswordInput(attrs={"placeholder": "비밀번호를 한번 더 입력하세요"}),
        label_suffix="",
    )

    account_name = forms.CharField(
        label="이름",
        max_length=10,
        widget=forms.TextInput(attrs={"placeholder": "이름을 입력하세요"}),
        label_suffix="",
    )

    phone_number = forms.CharField(
        label="전화번호",
        max_length=11,
        widget=forms.TextInput(attrs={"placeholder": "숫자만 입력하세요"}),
        label_suffix="",
    )

    nickname = forms.CharField(
        label="닉네임",
        max_length=100,
        label_suffix="",
        widget=forms.TextInput(attrs={"placeholder": "부적절한 닉네임은 제재를 받을 수 있습니다"}),
    )
    email = forms.EmailField(label="이메일", label_suffix="")

    def clean_username(self):
        username = self.cleaned_data.get("username")
        try:
            user = models.User.objects.get(username=username)
            raise ValidationError("중복된 아이디 입니다. 사용하실 수 없습니다")
        except ObjectDoesNotExist:
            return username

    def clean_password(self):
        password = self.cleaned_data.get("password")

        if validate_password(password) == None:
            return password

        else:
            raise ValidationError("사용할 수 없는 비밀번호입니다.")

    def clean_password_re(self):
        password = self.cleaned_data.get("password")
        password_re = self.cleaned_data.get("password_re")
        if password == password_re:
            return password_re
        else:
            raise ValidationError("비밀번호가 일치하지 않습니다")

    def save(self):
        username = self.cleaned_data.get("username")
        password_re = self.cleaned_data.get("password_re")
        account_name = self.cleaned_data.get("account_name")
        phone_number = self.cleaned_data.get("phone_number")
        nickname = self.cleaned_data.get("nickname")
        email = self.cleaned_data.get("email")

        user = models.User.objects.create_user(
            username, email=email, password=password_re
        )

        user.first_name = ""
        user.last_name = ""
        user.account_name = account_name
        user.phone_number = phone_number
        user.nickname = nickname

        user.save()


class FindMyIdForm(forms.Form):
    account_name = forms.CharField(
        label="이름", widget=forms.TextInput(attrs={"placeholder": "이름을 입력해주세요"})
    )
    email = forms.EmailField(
        label="이메일", widget=forms.TextInput(attrs={"placeholder": "이메일을 입력해주세요"})
    )


class MyPasswordResetForm(PasswordResetForm):
    username = forms.CharField(
        label="아이디", widget=forms.TextInput(attrs={"placeholder": "아이디를 입력해주세요"})
    )

    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(
            attrs={"autocomplete": "email", "placeholder": "이메일을 입력해주세요"}
        ),
    )


class SocialSignupForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""

    class Meta:
        model = models.User
        fields = (
            "username",
            "password",
            "email",
            "phone_number",
            "account_name",
            "nickname",
        )

        widgets = {
            "username": forms.HiddenInput,
            "password": forms.HiddenInput,
            "email": forms.HiddenInput,
            "phone_number": forms.HiddenInput,
            "account_name": forms.TextInput(attrs={"placeholder": "이름을 입력하세요"}),
            "nickname": forms.TextInput(attrs={"placeholder": "닉네임을 입력하세요"}),
        }

        labels = {"account_name": "이름", "nickname": "닉네임"}

    def save(self):
        user = models.User.objects.create_user(**self.cleaned_data)

        user.first_name = ""
        user.last_name = ""

        user.save()

templates/users/mypage/mypage_orders_ajax.html
{% load static %}
{% for detail in order_details %}
<div id="product" class="flex flex-row mb-5">
  <div class="w-2/12">
    <img id="product_img" src="{{detail.product.main_image.url}}">
  </div>
  <div id="product-contents" class="w-6/12">
    <div id="product_order_at2">{{detail.order_group.order_at | date}} 주문</div>
    <div class="flex flex-row">
      <div id="product_title">
        {% if detail.product.title|length > 16 %}
        {{detail.product.title|slice:"16"}}..
        {% else %}
        {{detail.product.title}}
        {% endif %}
      </div>
      <div id="slash">|</div>
      <div id="product_farm_name">{{detail.product.farmer.farm_name}}</div>

    </div>
    <div class="flex flex-row">
      <div id="product_price">{{detail.total_price}}원</div>
      <div id="product_quantity">{{detail.quantity}}개</div>
    </div>
    <div class="flex flex-row" id="delivery_status">

      {% if detail.status == 'preparing' %}
      <img id="delivery-status-icon" src="{% static 'images/users/preparing.svg' %}" alt="배송 준비 중 아이콘">
      <div>배송 준비 중</div>
      {% elif detail.status == 'shipping' %}
      <img id="delivery-status-icon" src="{% static 'images/users/delivering.svg' %}" alt="배송중 아이콘">
      <div>배송중</div>
      {% elif detail.status == 'delivery_complete' %}
      <img id="delivery-status-icon" src="{% static 'images/users/complete.svg' %}" alt="배송 완료 아이콘">
      <div>배송 완료</div>
      {% elif detail.status == 'cancel' %}
      <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
      <div>주문 취소</div>
      {% elif detail.status == 're_recept' %}
      <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
      <div>환불 접수</div>
      {% elif detail.status == 'ex_recept' %}
      <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
      <div>교환 접수</div>
      {% elif detail.status == 're_ex_approve' %}
      <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
      <div>환불/교환 승인</div>
      {% elif detail.status == 're_ex_deny' %}
      <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
      <div>환불/교환 거절</div>
      {% elif detail.status == 'wait' and detail.order_group.status == 'wait_vbank' %}
      <div>입금 대기</div>
      {% endif %}

    </div>
    <div class="flex flex-row"></div>
  </div>
  <div id="buttons-section" class="flex flex-col justify-center w-4/12 pl-6 pt-2">
    <div id="cart-button-section" class="flex justify-end items-center w-2/12">
      <div id="cartIn_btn" name="{{detail.product.pk}}" class="transition_element">장바구니 담기</div>
    </div>

    <div id="other-button-section" class="flex flex-col">

      <div id="see-product-btn" class="transition_element">
        <a href="{% url 'products:product_detail' detail.product.pk %}">
          무난이 보기
        </a>
      </div>

      {% if detail.status == 'delivery_complete' %}
      {% if detail.product.product_comments.exists == False %}
      <!-- <div id="reg-review-btn" class="transition_element" onclick=productCommentPopup({{detail.pk}})> -->
      <div id="reg-review-btn" class="transition_element" onclick="window.open('{% url 'user:product_comment_create' detail.pk %}')">
        <a>
          리뷰 쓰기
        </a>
      </div>
      {% else %}
      {% for review in detail.product_comments.all %}
      <!--수정 필요-->
      {% if review.product == detail.product %}
      <div id="reg-review-btn" class="transition_element" onclick="window.open('{% url 'user:product_comment_detail' review.pk %}', '', 'height=700 width=375')">
        <a>
          리뷰 보기
        </a>
      </div>
      {% endif %}
      {% endfor %}
      {% endif %}
      {% endif %}

      {% if detail.status == 'delivery_complete' %}
      <div id="reg-review-btn" class="transition_element" onclick="window.open('{% url 'orders:change_refund' detail.pk %}')">
        <a>
          환불/반품
        </a>
      </div>
      {% endif %}


      {% if detail.status == 'payment_complete' or detail.status == 'preparing' %}
      <div id="cancel-order-btn" class="transition_element">
        <a>
          주문 취소
        </a>
      </div>
      {% endif %}

      {% if detail.status == 'wait' and detail.order_group.status == 'wait_vbank' %}
      <div id="vbank_confirm_btn" class="transition_element" onclick="window.open('{% url 'user:vbank_account_confirm' detail.order_group.pk %}')">
        <a>가상계좌 확인</a>
      </div>
      {% endif %}

    </div>
  </div>
</div>
{% endfor %}
<!-- pagination section -->
<div class="flex justify-between w-36 mx-auto mt-8">
  <img src="{% static 'images/pagination/first_page.svg' %}" name='paginator' id='1' style="cursor: pointer">
  {% if order_details.has_previous %}
  <img src="{% static 'images/pagination/prev.svg' %}" name='paginator' id='{{order_details.previous_page_number}}' style="cursor: pointer">
  {% else %}
  <img src="{% static 'images/pagination/prev.svg' %}" name='paginator' id='1' style="cursor: pointer">
  {% endif %}

  <div>{{order_details.number}}</div>
  <div>/</div>
  <div>{{order_details.paginator.num_pages}}</div>

  {% if order_details.has_next %}
  <img src="{% static 'images/pagination/next.svg' %}" name='paginator' id='{{order_details.next_page_number}}' style="cursor: pointer">
  {% else %}
  <img src="{% static 'images/pagination/next.svg' %}" name='paginator' id='{{order_details.paginator.num_pages}}' style="cursor: pointer">
  {% endif %}
  <img src="{% static 'images/pagination/last_page.svg' %}" name='paginator' id='{{order_details.paginator.num_pages}}' style="cursor: pointer">
</div>

<script>
  PAGINATION_URL = 'orders-ajax/?page='
  PAGINATION_SECTION = '#products-section'
</script>
<script defer src="{% static 'js/pagination/pagination.js' %}"></script>