core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="main"),
    # path("index-test", views.landing_test, name="landing-test"),
    path("policy/disclaimer", views.disclaimer, name="disclaimer"),
    path("policy/personal-info", views.personal_info_usage, name="personal-info"),
    path("popup-callback", views.PopupCallback.as_view(), name="popup_callback"),
    path("completed_alert", views.CompletedAlert.as_view(), name="completed_alert"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("download/<str:filepath>/", views.download_file),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmers/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "farmers"

urlpatterns = [
    path("", views.farmers_page, name="farmers_page"),
    path("farmer_search/", views.farmer_search, name="farmer_search"),
    path("farmer_story_search/", views.farmer_story_search, name="farmer_story_search"),
    path("diary/create", views.farmer_story_create, name="farmer_story_create"),  # 추후 url 경로 수정하기
    path("diary/<int:pk>/update", views.farmer_story_update, name="farmer_story_update"),
    path("diary/<int:pk>", views.Story_Detail.as_view(), name="farmer_story_detail"),
    path("farm_cat_search/", views.farm_cat_search, name="farm_cat_search"),
    path("farm_tag_search/", views.farm_tag_search, name="farm_tag_search"),
    path("farmer_detail/<int:pk>/", views.farmer_detail, name="farmer_detail"),
    path(
        "farmer_detail/<int:pk>/products_ajax/",
        views.products_ajax,
        name="products_ajax",
    ),
    path(
        "farmer_detail/<int:pk>/diary_ajax/",
        views.diary_ajax,
        name="diary_ajax",
    ),
    path("apply/", views.farm_apply, name="farm_apply"),
    path("enroll/step/1/", views.enroll_page1, name="enroll_page1"),
    path("enroll/step/2/<int:consumerpk>/", views.enroll_page2, name="enroll_page2"),
    path("enroll/step/3/<int:farmerpk>/", views.enroll_page3, name="enroll_page3"),
    path("enroll/login", views.FarmEnrollLogin.as_view(), name="farm_enroll_login"),
    # farmer mypage
    path(
        "mypage/info/update",
        views.FarmerMyPageInfoManage.as_view(),
        name="farmer_mypage_info_update",
    ),
    path("mypage/info/farm_news/", views.farm_news_update, name="farm_news_update"),
    path(
        "mypage/products/",
        views.FarmerMyPageProductManage.as_view(),
        name="farmer_mypage_product",
    ),
    path(
        "mypage/orders",
        views.FarmerMyPageOrderManage.as_view(),
        name="farmer_mypage_order",
    ),
    path(
        "mypage/orders/state",
        views.farmer_mypage_order_state_update,
        name="farmer_mypage_order_state_update",
    ),
    path(
        "mypage/payment",
        views.FarmerMyPagePaymentManage.as_view(),
        name="farmer_mypage_payment",
    ),
    path(
        "mypage/notifications/",
        views.FarmerMyPageNotificationManage.as_view(),
        name="farmer_mypage_notification",
    ),
    path(
        "mypage/reviews-qnas/",
        views.FarmerMyPageReviewQnAManage.as_view(),
        name="farmer_mypage_review_qna",
    ),
    path(
        "mypage/reviews-qnas/<int:pk>/answer",
        views.FarmerMypageQuestionAnswer.as_view(),
        name="farmer_mypage_question_answer",
    ),
    path(
        "mypage/reviews-qnas/review/<int:pk>/answer",
        views.FarmerMypageReviewAnswer.as_view(),
        name="farmer_mypage_review_answer",
    ),
    path("mypage/notice", views.FarmerMyPageNotice.as_view(), name="farmer_mypage_notice"),
    # mypage pagination ajax url
    path(
        "mypage/notifications/notification_ajax/",
        views.notification_ajax,
        name="notification_ajax",
    ),
    path("mypage/reviews-qnas/qna-ajax/", views.qna_ajax, name="qna_ajax"),
    path("mypage/reviews-qnas/review-ajax/", views.review_ajax, name="review_ajax"),
    # mypage popups url
    path(
        "mypage/orders/list_excel",
        views.FarmerMypageGetOrderList.as_view(),
        name="farmer_mypage_get_order_list",
    ),
    path(
        "mypage/orders/list_excel_ajax",
        views.get_order_list_excel,
        name="farmer_mypage_get_order_list_ajax",
    ),
    path(
        "mypage/orders/check",
        views.FarmerMyPageOrderCheckPopup.as_view(),
        name="farmer_mypage_order_check_popup",
    ),
    path(
        "mypage/orders/cancel",
        views.FarmerMypageOrderCancelPopup.as_view(),
        name="farmer_mypage_order_cancel_popup",
    ),
    path(
        "mypage/orders/invoice",
        views.FarmerMypageInvoiceUpdatePopup.as_view(),
        name="farmer_mypage_invoice_update_popup",
    ),
    path(
        "mypage/product/update",
        views.FarmerMypageProductUpdatePopup.as_view(),
        name="farmer_mypage_product_update",
    ),
    path(
        "mypage/product/update/<int:pk>",
        views.FarmerMyPageProductStateUpdate.as_view(),
        name="farmer_mypage_product_state_update",
    ),
    path(
        "mypage/orders/refund/request/check",
        views.FarmerMyPageRefundRequestCheckPopup.as_view(),
        name="farmer_mypage_refund_check_popup",
    ),
    path(
        "mypage/orders/exchange/request/check",
        views.FarmerMyPageExchangeRequestCheckPopup.as_view(),
        name="farmer_mypage_exchange_check_popup",
    ),
    path(
        "mypage/popup-callback",
        views.FarmerMypagePopupCallback.as_view(),
        name="popup_callback",
    ),
    path("modal/farmer-sub", views.farmer_subs_modal, name="farmer_subs_modal"),
]

orders/urls.py
from django.urls import path, include
from . import views, cron


app_name = "orders"

urlpatterns = [
    path("orderingCart/", views.orderingCart, name="ordering_cart"),
    path("payment/update/<int:pk>/", views.payment_update, name="payment_update"),
    path("payment/", views.payment_create, name="payment_create"),
    path("payment/change-address", views.changeAddressAjax, name="payment_change-address"),
    # path('payment/success', views.payment_success, name="payment_success"),
    path("payment/fail", views.payment_fail, name="payment_fail"),
    path("payment/valid", views.payment_valid, name="payment_valid"),
    path("payment/vbank-progress", views.vbank_progess, name="vbank_progess"),
    path("payment/vbank-deposit", views.vbank_deposit, name="vbank_deposit"),
    path(
        "payment/vbank-template-test",
        views.vbank_template_test,
        name="vbank_template_test",
    ),
    path("payment/cancel/<int:pk>", views.order_cancel, name="payment_cancel"),
    # path('payment_fail', views.fail_test, name="fail_test"), 결제취소 창 테스트용 path
    path("change-refund/<int:pk>", views.create_change_or_refund, name="change_refund"),
    path("payment/subscribe", views.sub_modal, name="payment_success_modal"),
    path("payment/gift", views.payment_create_gift, name="payment_gift"),
    path("payment/gift/update", views.payment_update_gift, name="payment_gift_update"),
    path("payment/gift/valid", views.payment_valid_gift, name="payment_gift_valid"),
    path(
        "payment/gift/popup/address",
        views.delivery_address_update,
        name="payment_gift_delivery_update",
    ),
    path(
        "payment/gift/popup/order",
        views.payment_gift_order_list_popup,
        name="payment_gift_order_list",
    ),
    path(
        "payment/calculate-delivery-fee",
        views.calculate_delivery_fee,
        name="calculate_delivery_fee",
    ),
    # crontab actions
    path("cron/delete-pendings", cron.delete_waiting_orders, name="delete_pending_orders"),
    # temp test
    path("kafka", views.tmp, name="kafka_test"),
]

users/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_login_callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("signup_kakao", views.SocialSignup.as_view(), name="kakao_signup"),
    path(
        "signup/terms_of_service",
        views.terms_of_service_popup,
        name="signup_terms_of_service",
    ),
    path("signup/personal_info", views.personal_info_popup, name="signup_personal_info"),
    path("signup/id_validation/", views.idValidation, name="id_validation"),
    path(
        "signup/nickname_validation/",
        views.nicknameValidation,
        name="nickname_validation",
    ),
    path("signup/email_validation/", views.emailValidation, name="email_validation"),
    path(
        "signup/phone_number_validation/",
        views.phoneNumberValidation,
        name="phone_number_validation",
    ),
    path(
        "signup/phone_number_authentication/",
        views.phoneNumberAuthentication,
        name="phone_number_authentication",
    ),
    path("password_reset/", views.MyPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.MyPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.MyPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.MyPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("mypage/<slug:cat>", views.mypage, name="mypage"),
    path("editor_mypage/", views.EditorMyPage.as_view(), name="editor_mypage"),
    path(
        "editor_mypage/comments",
        views.EditorMyPage_Comments.as_view(),
        name="editor_mypage_comments",
    ),
    path(
        "editor_mypage/info",
        views.EditorMypage_Info.as_view(),
        name="editor_mypage_info",
    ),
    path("find_my_id/", views.FindMyIdView.as_view(), name="find_my_id"),
    path("find_my_id/complete", views.FindMyIdView.as_view(), name="find_my_id_complete"),
    path("find_my_id/failed", views.FindMyIdFailView.as_view(), name="find_my_id_failed"),
    path("cartIn/", views.CartInAjax, name="cartInAjax"),
    path("cartOut/", views.cartOutAjax, name="cartOutAjax"),
    path("subs/", views.subs, name="subs"),
    path("cancelSubs/", views.cancelSubs, name="cancelSubs"),
    path("wish/", views.wish, name="wish"),
    path("cancelWish/", views.cancelWish, name="cancelWish"),
    path("infoUpdate/", views.infoUpdate, name="infoUpdate"),
    path("profileUpdate/", views.profileUpdate, name="profileUpdate"),
    path("default-address", views.set_default_address_ajax, name="set_default_address_ajax"),
    path("test/", views.testview, name="testview"),
    path("product_refund_test/", views.product_refund, name="product_refund"),
    path("landing_test/", views.landing_test, name="landing_test"),
    # mypage popups
    path(
        "mypage/orders/<int:orderpk>/review/create",
        views.ProductCommentCreate.as_view(),
        name="product_comment_create",
    ),
    path(
        "mypage/orders/<int:grouppk>",
        views.vbank_account_confirm,
        name="vbank_account_confirm",
    ),
    path(
        "mypage/orders/review/<int:reviewpk>",
        views.productCommentDetail.as_view(),
        name="product_comment_detail",
    ),
    path("mypage/orders/list", views.OrderListPopup.as_view(), name="order_list_popup"),
    path("mypage/orders/shipping-info/<int:pk>", views.mypage_shipping_info_popup, name="mypage_shipping_info_popup"),
    # mypage pagination ajax
    path("mypage/orders-ajax/", views.mypage_orders_ajax, name="mypage_orders_ajax"),
]

templates/orders/gift/popups/payment_gift_popup_address_input.html
{% extends 'orders/gift/popups/payment_gift_popup_base.html' %}
{% load static %}
{% block popup_title %}선물하기 주소 입력{% endblock %}
{% with order_group=order_detail.order_group %}
{% block popup_content %}

<section id="gift_address_input_section">


    <h1 class="f-subtitle flex flex-col items-center">
        {{order_detail.order_group.orderer_name}}님이 보내신 선물을 받기 위해<br>
        <b>주소를 입력해주세요!</b>
    </h1>
    <form method="post" class="flex flex-col items-center">
        {% csrf_token %}
        <div id="product-info-section" class="flex w-full flex-col  main-content-section">
            <div class="flex justify-center">
                <img src="{{order_detail.product.main_image.url}}" alt="" class="product-image">
                <div class="flex flex-col justify-between product-info">
                    <div class="flex flex-col">
                        <span class="f-content-label">{{order_detail.product.title}}</span>
                        <span class="f-content-data">{{order_detail.quantity}}개</span>
                    </div>
                    <div class="flex items-center">
                        <img src="{{order_detail.product.farmer.farmer_profile.url}}" alt="" class="farmer-profile">
                        <span class="f-desc-small">{{order_detail.product.farmer.farm_name}}</span>
                    </div>
                </div>
            </div>
            <div id="address-input-section" class="flex flex-col items-center">
                <h2 class="f-desc-label">받는 분 주소</h2>
                <div class="flex w-full justify-between">
                    <input type="text" name='sigungu' class="address-input flex-1" v-model="sigungu" @click='handleAddressFindClick' readonly>
                    <button class="address-find-button f-desc-small" @click='handleAddressFindClick' type="button">
                        주소 찾기
                    </button>
                </div>
                <input type="text" name="detail" class="address-input w-full" v-model="detail" ref="detail">
                <input type="hidden" name="zipCode" v-model="zipCode">
            </div>
        </div>
        <button class="f-primary-button f-button-confirm mt-80" type="submit">확인</button>
    </form>
</section>
{% endblock %}
{% endwith %}
{% block scripts %}
<script src="{% static 'js/orders/popups/payment_gift_popup_address_input.js' %}"></script>
{% endblock %}

templates/orders/gift/popups/payment_gift_popup_address_input_complete.html
{% extends 'orders/gift/popups/payment_gift_popup_base.html' %}
{% load static %}
{% block popup_title %}선물하기 주소 입력 완료{% endblock %}
{% block popup_content %}
{% with farmer=order_detail.product.farmer %}
<section id="gift_address_input_section">
    <h1 class="f-subtitle flex flex-col items-center">
        <span class=" f-title mb-10">주소 입력이 완료되었습니다.</span>
        선물이 농가에서 출발할 때 알려드릴게요!
    </h1>

    <div class="flex justify-between w-full mb-10 mt-80">
        <button class="f-secondary-button" onclick="location.href = `{% url 'farmers:farmer_detail' farmer.pk %}`">농가 알아보기</button>
        <button class="f-secondary-button" onclick="location.href=`{% url 'orders:payment_gift_order_list' %}?odmn={{order_detail.encrypt_odmn}}`">배송 정보 확인</button>
    </div>

    <button class="f-primary-button f-button-confirm" onclick="location.href = `{% url 'core:main' %}`">확인</button>
</section>
{% endwith %}
{% endblock %}

templates/orders/gift/popups/payment_gift_popup_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block popup_title %}{% endblock %} | 피키팜</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'images/mainlogo_small.svg' %}">
    <link rel="stylesheet" href="{% static 'css/orders/popups/order_gift_popup_base.css' %}">
    {% block stylesheet %}
    {% endblock stylesheet %}
</head>

<body>
    <header class="flex">
        <img src="{% static 'images/mainlogo_small.svg' %}" alt="피키팜 메인로고" id="main-logo" class="mx-auto">
    </header>
    {% block popup_content %}
    {% endblock %}

</body>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script defer src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script defer src="{% static 'js/base/addressHandler.js' %}"></script>
{% block scripts %}
{% endblock %}

</html>

templates/orders/gift/popups/payment_gift_popup_order_list.html
{% extends 'orders/gift/popups/payment_gift_popup_base.html' %}
{% load static %}
{% block popup_title %}상품 배송 정보 확인{% endblock %}
{% block popup_content %}


{% with farmer=order_detail.product.farmer %}
<section id="order-list-section">
    <h1 class="f-title">상품 배송 정보 확인</h1>
    <div id="product-info-section" class="flex w-full flex-col  main-content-section">
        <div class="flex justify-center">
            <img src="{{order_detail.product.main_image.url}}" alt="" class="product-image">
            <div class="flex flex-col justify-between product-info">
                <div class="flex flex-col">
                    <span class="f-content-label">{{order_detail.product.title}}</span>
                    <span class="f-content-data">{{order_detail.quantity}}개</span>
                </div>
                <div class="flex items-center deliver-status">
                    <span class="f-desc-label">{{order_detail.get_status_display}}</span>
                </div>
            </div>
        </div>
        <div class="flex justify-between items-center farmer-info">
            <div class="flex items-center">
                <img src="{{farmer.farmer_profile.url}}" alt="" class="farmer-profile">
                <span class="f-desc-label">{{farmer.farm_name}}</span>
            </div>
            <button class="farmer-page-button" onclick="location.href = `{% url 'farmers:farmer_detail' farmer.pk %}`">
                미니홈피 방문하기
            </button>
        </div>
        <div class="receiver-info grid mx-auto">
            <span class="receiver-info-label f-content-label">수령인</span>
            <span class="receiver-info-label f-content-label">전화번호</span>
            <span class="receiver-info-label f-content-label">주소</span>
            <span class="receiver-info-data f-content-data">{{order_detail.rev_name_gift}}</span>
            <span class="receiver-info-data f-content-data">{{order_detail.rev_phone_number_gift}}</span>
            <span class="receiver-info-data f-content-data">{{order_detail.rev_address_gift}}</span>
        </div>
    </div>
    <div class="flex justify-between button-group">
        <button class="f-primary-button f-button-signup" onclick="location.href = `{% url 'users:signup' %}`">회원가입
            하기</button>
        <button class="f-primary-button f-button-confirm" onclick="location.href = `{% url 'core:main' %}`">확인</button>
    </div>
</section>
{% endwith %}
{% endblock %}