core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="main"),
    # path("index-test", views.landing_test, name="landing-test"),
    path("policy/disclaimer", views.disclaimer, name="disclaimer"),
    path("policy/personal-info", views.personal_info_usage, name="personal-info"),
    path("popup-callback", views.PopupCallback.as_view(), name="popup_callback"),
    path("completed_alert", views.CompletedAlert.as_view(), name="completed_alert"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("download/<str:filepath>/", views.download_file),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmers/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "farmers"

urlpatterns = [
    path("", views.farmers_page, name="farmers_page"),
    path("farmer_search/", views.farmer_search, name="farmer_search"),
    path("farmer_story_search/", views.farmer_story_search, name="farmer_story_search"),
    path("diary/create", views.farmer_story_create, name="farmer_story_create"),  # 추후 url 경로 수정하기
    path("diary/<int:pk>/update", views.farmer_story_update, name="farmer_story_update"),
    path("diary/<int:pk>", views.Story_Detail.as_view(), name="farmer_story_detail"),
    path("farm_cat_search/", views.farm_cat_search, name="farm_cat_search"),
    path("farm_tag_search/", views.farm_tag_search, name="farm_tag_search"),
    path("farmer_detail/<int:pk>/", views.farmer_detail, name="farmer_detail"),
    path(
        "farmer_detail/<int:pk>/products_ajax/",
        views.products_ajax,
        name="products_ajax",
    ),
    path(
        "farmer_detail/<int:pk>/diary_ajax/",
        views.diary_ajax,
        name="diary_ajax",
    ),
    path("apply/", views.farm_apply, name="farm_apply"),
    path("enroll/step/1/", views.enroll_page1, name="enroll_page1"),
    path("enroll/step/2/<int:consumerpk>/", views.enroll_page2, name="enroll_page2"),
    path("enroll/step/3/<int:farmerpk>/", views.enroll_page3, name="enroll_page3"),
    path("enroll/login", views.FarmEnrollLogin.as_view(), name="farm_enroll_login"),
    # farmer mypage
    path(
        "mypage/info/update",
        views.FarmerMyPageInfoManage.as_view(),
        name="farmer_mypage_info_update",
    ),
    path("mypage/info/farm_news/", views.farm_news_update, name="farm_news_update"),
    path(
        "mypage/products/",
        views.FarmerMyPageProductManage.as_view(),
        name="farmer_mypage_product",
    ),
    path(
        "mypage/orders",
        views.FarmerMyPageOrderManage.as_view(),
        name="farmer_mypage_order",
    ),
    path(
        "mypage/orders/state",
        views.farmer_mypage_order_state_update,
        name="farmer_mypage_order_state_update",
    ),
    path(
        "mypage/payment",
        views.FarmerMyPagePaymentManage.as_view(),
        name="farmer_mypage_payment",
    ),
    path(
        "mypage/notifications/",
        views.FarmerMyPageNotificationManage.as_view(),
        name="farmer_mypage_notification",
    ),
    path(
        "mypage/reviews-qnas/",
        views.FarmerMyPageReviewQnAManage.as_view(),
        name="farmer_mypage_review_qna",
    ),
    path(
        "mypage/reviews-qnas/<int:pk>/answer",
        views.FarmerMypageQuestionAnswer.as_view(),
        name="farmer_mypage_question_answer",
    ),
    path(
        "mypage/reviews-qnas/review/<int:pk>/answer",
        views.FarmerMypageReviewAnswer.as_view(),
        name="farmer_mypage_review_answer",
    ),
    path("mypage/notice", views.FarmerMyPageNotice.as_view(), name="farmer_mypage_notice"),
    # mypage pagination ajax url
    path(
        "mypage/notifications/notification_ajax/",
        views.notification_ajax,
        name="notification_ajax",
    ),
    path("mypage/reviews-qnas/qna-ajax/", views.qna_ajax, name="qna_ajax"),
    path("mypage/reviews-qnas/review-ajax/", views.review_ajax, name="review_ajax"),
    # mypage popups url
    path(
        "mypage/orders/list_excel",
        views.FarmerMypageGetOrderList.as_view(),
        name="farmer_mypage_get_order_list",
    ),
    path(
        "mypage/orders/list_excel_ajax",
        views.get_order_list_excel,
        name="farmer_mypage_get_order_list_ajax",
    ),
    path(
        "mypage/orders/check",
        views.FarmerMyPageOrderCheckPopup.as_view(),
        name="farmer_mypage_order_check_popup",
    ),
    path(
        "mypage/orders/cancel",
        views.FarmerMypageOrderCancelPopup.as_view(),
        name="farmer_mypage_order_cancel_popup",
    ),
    path(
        "mypage/orders/invoice",
        views.FarmerMypageInvoiceUpdatePopup.as_view(),
        name="farmer_mypage_invoice_update_popup",
    ),
    path(
        "mypage/product/update",
        views.FarmerMypageProductUpdatePopup.as_view(),
        name="farmer_mypage_product_update",
    ),
    path(
        "mypage/product/update/<int:pk>",
        views.FarmerMyPageProductStateUpdate.as_view(),
        name="farmer_mypage_product_state_update",
    ),
    path(
        "mypage/orders/refund/request/check",
        views.FarmerMyPageRefundRequestCheckPopup.as_view(),
        name="farmer_mypage_refund_check_popup",
    ),
    path(
        "mypage/orders/exchange/request/check",
        views.FarmerMyPageExchangeRequestCheckPopup.as_view(),
        name="farmer_mypage_exchange_check_popup",
    ),
    path(
        "mypage/popup-callback",
        views.FarmerMypagePopupCallback.as_view(),
        name="popup_callback",
    ),
    path("modal/farmer-sub", views.farmer_subs_modal, name="farmer_subs_modal"),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("list/", views.StoreList.as_view(), name="store_list"),
    path("list/<slug:cat>/", views.store_list_cat, name="store_list_category"),
    path("detail/<int:pk>/", views.product_detail, name="product_detail"),
    path("detail/qna_paginator/", views.question_paging, name="qna_paginator"),
    # path('enroll/', views.product_enroll, name="product_enroll"),
    # path('delete/<int:pk>/', views.product_delete, name="product_delete"),
    # path('update/<int:pk>/', views.product_update, name="product_update"),
    path("question/create", views.create_question, name="question_create"),
    path("question/<int:pk>", views.read_qna, name="question_read"),
    # pagination
    path("detail/<int:pk>/comment_ajax/", views.comment_ajax, name="comment_ajax"),
    path("detail/<int:pk>/question_ajax/", views.question_ajax, name="question_ajax"),
    # EP
    path("get-db", views.get_product_EP, name="get_product_db"),
    path("get-db/daum", views.get_product_daum_EP, name="get_product_db_daum"),

]

templates/base/landing/siminwon/siminwon_landing_header.html
{% load static %}

<section class="siminwon-landing-wrapper" id="siminwon-landing-header">
    <article class="landing-content" id="landing-header-content">
        <div id="landing-header-content-wrap" class="flex flex-col">
            <div id="landing-header-tag">
                오픈 기념
            </div>
            <h2 class="landing-header-main-text">소개합니다, 올해 마지막</h2>
            <h1 class="landing-header-main-text" id="strong">시민원 무난이 홍로 사과</h1>
            <span id="landing-header-duration">10.07 ~ 매진시까지</span>
            <img class="landing-header-img" src="{% static 'images/landing/siminwon/underline_with_star.webp' %}" alt="" id="underline-star">
        </div>
        <img class="landing-header-img" src="{% static 'images/landing/siminwon/header_apple_single.webp' %}" alt="시민원 사과" id="apple-single">
        <img class="landing-header-img" src="{% static 'images/landing/siminwon/header_apple_double.webp' %}" alt="" id="apple-double">
    </article>
</section>

templates/base/landing/siminwon/siminwon_landing_page.html
{% extends 'base/base_for_index.html' %}
{% load static %}

{% block title_name %} 피키팜 : 까다롭게 선택하다 {% endblock title_name %}
{% block stylesheet %}
<link rel="icon" href="{% static 'images/index/mainlogo.svg' %}">
<link rel="stylesheet" href="{% static 'css/base/landing/siminwon_landing.css' %}">
<link rel="stylesheet" href="{% static 'css/base/landing/landing_page.css' %}">

{% endblock stylesheet %}
{% block main_content %}
{% include 'base/main_slider.html' %}
{% include 'base/landing/siminwon/siminwon_landing_header.html' %}
{% include 'base/landing/siminwon/siminwon_landing_page1.html' %}
{% include 'base/landing/siminwon/siminwon_landing_page2.html' %}
{% include 'base/landing/landing_page4.html' %}
{% include 'base/landing/landing_page1.html' %}
{% include 'base/landing/landing_page2.html' %}
{% include 'base/landing/landing_page3.html' %}
<script>

</script>
{% endblock main_content %}

templates/base/landing/siminwon/siminwon_landing_page1.html
{% load static %}

<section class="siminwon-landing-wrapper" id="siminwon-section1">
    <article class="landing-content" id="landing-siminwon-section1">
        <div id="siminwon-section1-product-content">
            <div class="flex justify-center mb-2" id="siminwon-section1-num-wrap">
                <div id="siminwon-section1-num">01</div>
            </div>
            <div class="text-center" id="siminwon-section1-title-wrap">
                <h1 id="siminwon-section1-title">연중 제일 달달한 사과, 홍로</h1>
            </div>
            <div id="siminwon-section1-desc-wrap" class="flex justify-center">
                <div class="siminwon-section1-desc">
                    <span class="siminwon-section1-desc-number">01</span>
                    <p class="siminwon-section1-desc-content">
                        우리나라<br />
                        생산 품종 중<br />
                        <strong>제일 높은 당도</strong>
                    </p>
                </div>
                <div class="siminwon-section1-desc">
                    <span class="siminwon-section1-desc-number">02</span>
                    <p class="siminwon-section1-desc-content">
                        신선도유지제를<br />
                        쓰지 않은<br />
                        <strong>자연스러움</strong>
                    </p>
                </div>
                <div class="siminwon-section1-desc">
                    <span class="siminwon-section1-desc-number">03</span>
                    <p class="siminwon-section1-desc-content">
                        특유의<br />
                        <strong>부드러운 향</strong>
                    </p>
                </div>
            </div>
        </div>
    </article>
</section>

templates/base/landing/siminwon/siminwon_landing_page2.html
{% load static %}

<section class="siminwon-landing-wrapper" id="siminwon-section2">
    <article class="landing-content" id="landing-siminwon-section2">
        <div class="siminwon-section2-wrapper">
            <div id="siminwon-section2-product-content">
                <div class="flex justify-center mb-2" id="siminwon-section2-num-wrap">
                    <div id="siminwon-section2-num">02</div>
                </div>
                <div class="text-center" id="siminwon-section2-title-wrap">
                    <h1 id="siminwon-section2-title">외모만 보고 지나치기엔 아쉬울</h1>
                    <h2 id="siminwon-section2-subtitle">가격과 품질!</h2>
                </div>
                <div class="" id="product-list-wrapper">
                    <a href="{% url 'products:product_detail' 19 %}">
                        <div class="product-wrapper zoom-on-hover">
                            <div class="product-image-wrapper">
                                <img src="{% static 'images/landing/siminwon/apple-small.png' %}" alt="">
                            </div>
                            <div class="product-desc-wrapper">
                                <div class="product-title md:flex md:flex-row">
                                    <div class="mb-1 mr-1">소과 3kg</div>
                                    <div>(15~18개입)</div>
                                </div>
                                <div class="product-price">12,000원</div>
                                <div class="flex flex-row product-tag-wrapper justify-between">
                                    <div class="ugly_tag">무난이 작물</div>
                                    <div>+</div>
                                    <div class="normal_tag">일반 작물</div>
                                </div>
                            </div>
                        </div>
                    </a>
                    <!-- <a href="{% url 'products:product_detail' 18 %}">
                        <div class="product-wrapper zoom-on-hover">
                            <img class="event-badge" src="{% static 'images/landing/siminwon/event_badge.svg' %}" alt="">
                            <div class="product-image-wrapper">
                                <img src="{% static 'images/landing/siminwon/apple-small-medium.png' %}" alt="">
                            </div>
                            <div class="product-desc-wrapper">
                                <div class="product-title md:flex md:flex-row">
                                    <div class="mb-1 mr-1">중소과 5kg</div>
                                    <div>(21~23개입)</div>
                                </div>
                                <div class="product-price">18,000원</div>
                                <div class="flex flex-row product-tag-wrapper justify-between">
                                    <div class="ugly_tag">무난이 작물</div>
                                    <div>+</div>
                                    <div class="normal_tag">일반 작물</div>
                                </div>
                            </div>
                        </div>
                    </a> -->
                    <!-- <a href="{% url 'products:product_detail' 17 %}">
                        <div class="product-wrapper zoom-on-hover">
                            <img class="event-badge" src="{% static 'images/landing/siminwon/event_badge.svg' %}" alt="">
                            <div class="product-image-wrapper">
                                <img src="{% static 'images/landing/siminwon/apple-medium.png' %}" alt="">
                            </div>
                            <div class="product-desc-wrapper">
                                <div class="product-title md:flex md:flex-row">
                                    <div class="mb-1 mr-1">중과 5kg</div>
                                    <div>(18~20개입)</div>
                                </div>
                                <div class="product-price">20,000원</div>
                                <div class="flex flex-row product-tag-wrapper justify-between">
                                    <div class="ugly_tag">무난이 작물</div>
                                    <div>+</div>
                                    <div class="normal_tag">일반 작물</div>
                                </div>
                            </div>
                        </div>
                    </a> -->
                </div>
            </div>
            <div class="flex flex-row" id="siminwon-section2-farmer-content">
                <div id="farmer-profile">
                    <img src="{% static 'images/landing/siminwon/farmer_profile.png' %}" alt="">
                </div>
                <div class="flex flex-col items-center justify-center" id="farmer-desc">
                    <h1 id="farmer-title">사과의 자연스러움을 추구하다, 시민원</h1>
                    {% if siminwon != None %}
                    <a href="{% url 'farmer:farmer_detail' siminwon.pk %}">
                        <div class="text-center zoom-on-hover" id="farmer-homepage-btn">미니홈페이지 보러가기</div>
                    </a>
                    {% else %}
                    <div class="text-center zoom-on-hover" id="farmer-homepage-btn">미니홈페이지 보러가기</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </article>
</section>