core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name="main"),
    # path("index-test", views.landing_test, name="landing-test"),
    path("policy/disclaimer", views.disclaimer, name="disclaimer"),
    path("policy/personal-info", views.personal_info_usage, name="personal-info"),
    path("popup-callback", views.PopupCallback.as_view(), name="popup_callback"),
    path("completed_alert", views.CompletedAlert.as_view(), name="completed_alert"),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("download/<str:filepath>/", views.download_file),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

farmers/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = "farmers"

urlpatterns = [
    path("", views.farmers_page, name="farmers_page"),
    path("farmer_search/", views.farmer_search, name="farmer_search"),
    path("farmer_story_search/", views.farmer_story_search, name="farmer_story_search"),
    path("diary/create", views.farmer_story_create, name="farmer_story_create"),  # 추후 url 경로 수정하기
    path("diary/<int:pk>/update", views.farmer_story_update, name="farmer_story_update"),
    path("diary/<int:pk>", views.Story_Detail.as_view(), name="farmer_story_detail"),
    path("farm_cat_search/", views.farm_cat_search, name="farm_cat_search"),
    path("farm_tag_search/", views.farm_tag_search, name="farm_tag_search"),
    path("farmer_detail/<int:pk>/", views.farmer_detail, name="farmer_detail"),
    path(
        "farmer_detail/<int:pk>/products_ajax/",
        views.products_ajax,
        name="products_ajax",
    ),
    path(
        "farmer_detail/<int:pk>/diary_ajax/",
        views.diary_ajax,
        name="diary_ajax",
    ),
    path("apply/", views.farm_apply, name="farm_apply"),
    path("enroll/step/1/", views.enroll_page1, name="enroll_page1"),
    path("enroll/step/2/<int:consumerpk>/", views.enroll_page2, name="enroll_page2"),
    path("enroll/step/3/<int:farmerpk>/", views.enroll_page3, name="enroll_page3"),
    path("enroll/login", views.FarmEnrollLogin.as_view(), name="farm_enroll_login"),
    # farmer mypage
    path(
        "mypage/info/update",
        views.FarmerMyPageInfoManage.as_view(),
        name="farmer_mypage_info_update",
    ),
    path("mypage/info/farm_news/", views.farm_news_update, name="farm_news_update"),
    path(
        "mypage/products/",
        views.FarmerMyPageProductManage.as_view(),
        name="farmer_mypage_product",
    ),
    path(
        "mypage/orders",
        views.FarmerMyPageOrderManage.as_view(),
        name="farmer_mypage_order",
    ),
    path(
        "mypage/orders/state",
        views.farmer_mypage_order_state_update,
        name="farmer_mypage_order_state_update",
    ),
    path(
        "mypage/payment",
        views.FarmerMyPagePaymentManage.as_view(),
        name="farmer_mypage_payment",
    ),
    path(
        "mypage/notifications/",
        views.FarmerMyPageNotificationManage.as_view(),
        name="farmer_mypage_notification",
    ),
    path(
        "mypage/reviews-qnas/",
        views.FarmerMyPageReviewQnAManage.as_view(),
        name="farmer_mypage_review_qna",
    ),
    path(
        "mypage/reviews-qnas/<int:pk>/answer",
        views.FarmerMypageQuestionAnswer.as_view(),
        name="farmer_mypage_question_answer",
    ),
    path(
        "mypage/reviews-qnas/review/<int:pk>/answer",
        views.FarmerMypageReviewAnswer.as_view(),
        name="farmer_mypage_review_answer",
    ),
    path("mypage/notice", views.FarmerMyPageNotice.as_view(), name="farmer_mypage_notice"),
    # mypage pagination ajax url
    path(
        "mypage/notifications/notification_ajax/",
        views.notification_ajax,
        name="notification_ajax",
    ),
    path("mypage/reviews-qnas/qna-ajax/", views.qna_ajax, name="qna_ajax"),
    path("mypage/reviews-qnas/review-ajax/", views.review_ajax, name="review_ajax"),
    # mypage popups url
    path(
        "mypage/orders/list_excel",
        views.FarmerMypageGetOrderList.as_view(),
        name="farmer_mypage_get_order_list",
    ),
    path(
        "mypage/orders/list_excel_ajax",
        views.get_order_list_excel,
        name="farmer_mypage_get_order_list_ajax",
    ),
    path(
        "mypage/orders/check",
        views.FarmerMyPageOrderCheckPopup.as_view(),
        name="farmer_mypage_order_check_popup",
    ),
    path(
        "mypage/orders/cancel",
        views.FarmerMypageOrderCancelPopup.as_view(),
        name="farmer_mypage_order_cancel_popup",
    ),
    path(
        "mypage/orders/invoice",
        views.FarmerMypageInvoiceUpdatePopup.as_view(),
        name="farmer_mypage_invoice_update_popup",
    ),
    path(
        "mypage/product/update",
        views.FarmerMypageProductUpdatePopup.as_view(),
        name="farmer_mypage_product_update",
    ),
    path(
        "mypage/product/update/<int:pk>",
        views.FarmerMyPageProductStateUpdate.as_view(),
        name="farmer_mypage_product_state_update",
    ),
    path(
        "mypage/orders/refund/request/check",
        views.FarmerMyPageRefundRequestCheckPopup.as_view(),
        name="farmer_mypage_refund_check_popup",
    ),
    path(
        "mypage/orders/exchange/request/check",
        views.FarmerMyPageExchangeRequestCheckPopup.as_view(),
        name="farmer_mypage_exchange_check_popup",
    ),
    path(
        "mypage/popup-callback",
        views.FarmerMypagePopupCallback.as_view(),
        name="popup_callback",
    ),
    path("modal/farmer-sub", views.farmer_subs_modal, name="farmer_subs_modal"),
]

orders/urls.py
from django.urls import path, include
from . import views, cron


app_name = "orders"

urlpatterns = [
    path("orderingCart/", views.orderingCart, name="ordering_cart"),
    path("payment/update/<int:pk>/", views.payment_update, name="payment_update"),
    path("payment/", views.payment_create, name="payment_create"),
    path("payment/change-address", views.changeAddressAjax, name="payment_change-address"),
    # path('payment/success', views.payment_success, name="payment_success"),
    path("payment/fail", views.payment_fail, name="payment_fail"),
    path("payment/valid", views.payment_valid, name="payment_valid"),
    path("payment/vbank-progress", views.vbank_progess, name="vbank_progess"),
    path("payment/vbank-deposit", views.vbank_deposit, name="vbank_deposit"),
    path(
        "payment/vbank-template-test",
        views.vbank_template_test,
        name="vbank_template_test",
    ),
    path("payment/cancel/<int:pk>", views.order_cancel, name="payment_cancel"),
    # path('payment_fail', views.fail_test, name="fail_test"), 결제취소 창 테스트용 path
    path("change-refund/<int:pk>", views.create_change_or_refund, name="change_refund"),
    path("payment/subscribe", views.sub_modal, name="payment_success_modal"),
    path("payment/gift", views.payment_create_gift, name="payment_gift"),
    path("payment/gift/update", views.payment_update_gift, name="payment_gift_update"),
    path("payment/gift/valid", views.payment_valid_gift, name="payment_gift_valid"),
    path(
        "payment/gift/popup/address",
        views.delivery_address_update,
        name="payment_gift_delivery_update",
    ),
    path(
        "payment/gift/popup/order",
        views.payment_gift_order_list_popup,
        name="payment_gift_order_list",
    ),
    path(
        "payment/calculate-delivery-fee",
        views.calculate_delivery_fee,
        name="calculate_delivery_fee",
    ),
    # crontab actions
    path("cron/delete-pendings", cron.delete_waiting_orders, name="delete_pending_orders"),
    # temp test
    path("kafka", views.tmp, name="kafka_test"),
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path("list/", views.StoreList.as_view(), name="store_list"),
    path("list/<slug:cat>/", views.store_list_cat, name="store_list_category"),
    path("detail/<int:pk>/", views.product_detail, name="product_detail"),
    path("detail/qna_paginator/", views.question_paging, name="qna_paginator"),
    # path('enroll/', views.product_enroll, name="product_enroll"),
    # path('delete/<int:pk>/', views.product_delete, name="product_delete"),
    # path('update/<int:pk>/', views.product_update, name="product_update"),
    path("question/create", views.create_question, name="question_create"),
    path("question/<int:pk>", views.read_qna, name="question_read"),
    # pagination
    path("detail/<int:pk>/comment_ajax/", views.comment_ajax, name="comment_ajax"),
    path("detail/<int:pk>/question_ajax/", views.question_ajax, name="question_ajax"),
    # EP
    path("get-db", views.get_product_EP, name="get_product_db"),
    path("get-db/daum", views.get_product_daum_EP, name="get_product_db_daum"),

]

users/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("login/kakao/", views.kakao_login, name="kakao_login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao_login_callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("signup_kakao", views.SocialSignup.as_view(), name="kakao_signup"),
    path(
        "signup/terms_of_service",
        views.terms_of_service_popup,
        name="signup_terms_of_service",
    ),
    path("signup/personal_info", views.personal_info_popup, name="signup_personal_info"),
    path("signup/id_validation/", views.idValidation, name="id_validation"),
    path(
        "signup/nickname_validation/",
        views.nicknameValidation,
        name="nickname_validation",
    ),
    path("signup/email_validation/", views.emailValidation, name="email_validation"),
    path(
        "signup/phone_number_validation/",
        views.phoneNumberValidation,
        name="phone_number_validation",
    ),
    path(
        "signup/phone_number_authentication/",
        views.phoneNumberAuthentication,
        name="phone_number_authentication",
    ),
    path("password_reset/", views.MyPasswordResetView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        views.MyPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        views.MyPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.MyPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("mypage/<slug:cat>", views.mypage, name="mypage"),
    path("editor_mypage/", views.EditorMyPage.as_view(), name="editor_mypage"),
    path(
        "editor_mypage/comments",
        views.EditorMyPage_Comments.as_view(),
        name="editor_mypage_comments",
    ),
    path(
        "editor_mypage/info",
        views.EditorMypage_Info.as_view(),
        name="editor_mypage_info",
    ),
    path("find_my_id/", views.FindMyIdView.as_view(), name="find_my_id"),
    path("find_my_id/complete", views.FindMyIdView.as_view(), name="find_my_id_complete"),
    path("find_my_id/failed", views.FindMyIdFailView.as_view(), name="find_my_id_failed"),
    path("cartIn/", views.CartInAjax, name="cartInAjax"),
    path("cartOut/", views.cartOutAjax, name="cartOutAjax"),
    path("subs/", views.subs, name="subs"),
    path("cancelSubs/", views.cancelSubs, name="cancelSubs"),
    path("wish/", views.wish, name="wish"),
    path("cancelWish/", views.cancelWish, name="cancelWish"),
    path("infoUpdate/", views.infoUpdate, name="infoUpdate"),
    path("profileUpdate/", views.profileUpdate, name="profileUpdate"),
    path("default-address", views.set_default_address_ajax, name="set_default_address_ajax"),
    path("test/", views.testview, name="testview"),
    path("product_refund_test/", views.product_refund, name="product_refund"),
    path("landing_test/", views.landing_test, name="landing_test"),
    # mypage popups
    path(
        "mypage/orders/<int:orderpk>/review/create",
        views.ProductCommentCreate.as_view(),
        name="product_comment_create",
    ),
    path(
        "mypage/orders/<int:grouppk>",
        views.vbank_account_confirm,
        name="vbank_account_confirm",
    ),
    path(
        "mypage/orders/review/<int:reviewpk>",
        views.productCommentDetail.as_view(),
        name="product_comment_detail",
    ),
    path("mypage/orders/list", views.OrderListPopup.as_view(), name="order_list_popup"),
    path("mypage/orders/shipping-info/<int:pk>", views.mypage_shipping_info_popup, name="mypage_shipping_info_popup"),
    # mypage pagination ajax
    path("mypage/orders-ajax/", views.mypage_orders_ajax, name="mypage_orders_ajax"),
]

templates/users/mypage/user/order_list_popup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>주문목록 조회 | 피키팜
    </title>
    <link rel="stylesheet" href="{% static 'css/users/mypage/user/mypage_orders_mobile.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <h1>주문목록 조회</h1>
    <div id="products-section" class="mt-5 popup-wrapper">
        {% for detail in order_details %}
        <div id="product" class="flex flex-row mb-5">
            <div class="w-2/12">
                <img id="product_img" src="{{detail.product.main_image.url}}">
            </div>
            <div id="product-contents" class="w-6/12">
                <div id="product_order_at2">{{detail.order_group.order_at | date}} 주문</div>
                <div class="flex flex-row">
                    <div id="product_title">
                        {% if detail.product.title|length > 16 %}
                        {{detail.product.title|slice:"16"}}..
                        {% else %}
                        {{detail.product.title}}
                        {% endif %}
                    </div>
                    <div id="slash">|</div>
                    <div id="product_farm_name">{{detail.product.farmer.farm_name}}</div>

                </div>
                <div class="flex flex-row">
                    <div id="product_price">{{detail.total_price}}원</div>
                    <div id="product_quantity">{{detail.quantity}}개</div>
                </div>
                <div class="flex flex-row" id="delivery_status">

                    {% if detail.status == 'payment_complete' %}
                    <div>결제 완료</div>
                    {% elif detail.status == 'preparing' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/preparing.svg' %}" alt="배송 준비 중 아이콘">
                    <div>배송 준비 중</div>
                    {% elif detail.status == 'shipping' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/delivering.svg' %}" alt="배송중 아이콘">
                    <div>배송중</div>
                    {% elif detail.status == 'delivery_complete' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/complete.svg' %}" alt="배송 완료 아이콘">
                    <div>배송 완료</div>
                    {% elif detail.status == 'cancel' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
                    <div>주문 취소</div>
                    {% elif detail.status == 're_recept' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
                    <div>환불 접수</div>
                    {% elif detail.status == 'ex_recept' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
                    <div>교환 접수</div>
                    {% elif detail.status == 're_ex_approve' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
                    <div>환불/교환 승인</div>
                    {% elif detail.status == 're_ex_deny' %}
                    <img id="delivery-status-icon" src="{% static 'images/users/cancel.svg' %}" alt="주문 취소 아이콘">
                    <div>환불/교환 거절</div>
                    {% elif detail.status == 'wait' and group.status == 'wait_vbank' %}
                    <div>입금 대기</div>
                    {% endif %}

                </div>
                <div class="flex flex-row"></div>
            </div>
            <div id="buttons-section" class="flex justify-end w-4/12 pl-6 pt-2" style="justify-content: flex-end !important;">

                <div id="other-button-section" class="flex flex-col">

                    <div id="see-product-btn" class="transition_element">
                        <a href="{% url 'products:product_detail' detail.product.pk %}">
                            무난이 보기
                        </a>
                    </div>




                    {% if detail.status == 'payment_complete' %}
                    <div id="cancel-order-btn" class="transition_element" onclick="window.open('{% url 'orders:payment_cancel' detail.pk %}')">
                        <a>
                            주문 취소
                        </a>
                    </div>
                    {% endif %}

                    {% if detail.status == 'wait' and detail.order_group.status == 'wait_vbank' %}
                    <div id="vbank_confirm_btn" class="transition_element" onclick="window.open('{% url 'user:vbank_account_confirm' detail.order_group.pk %}')">
                        <a>가상계좌 확인</a>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>
        {% endfor %}

    </div>

</body>
<style>
    h1 {
        color: #5c6754;
        font-size: 2.5rem;
        text-align: center;
        font-weight: bold;

        margin: 2rem;
        margin-bottom: 5rem;

    }
</style>

</html>

templates/users/mypage/user/popup_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block popup_title %}{% endblock %} | 피키팜</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'images/mainlogo_small.svg' %}">
    <link rel="stylesheet" href="{% static 'css/orders/popups/order_gift_popup_base.css' %}">
    {% block stylesheet %}
    {% endblock stylesheet %}
</head>

<body>
    <header class="flex">
        <img src="{% static 'images/mainlogo_small.svg' %}" alt="피키팜 메인로고" id="main-logo" class="mx-auto">
    </header>
    {% block popup_content %}
    {% endblock %}

</body>
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script defer src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
<script defer src="{% static 'js/base/addressHandler.js' %}"></script>
{% block scripts %}
{% endblock %}

</html>

templates/users/mypage/user/product_exchange_complete.html
<!doctype html>
{% load static %}
<html lang='en'>

<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, user-scalable=no, initial-scale=1.0'>
    <link rel="stylesheet" href="{% static 'css/users/mypage/user/product_exchange_complete.css' %}" />
    <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>교환 신청 완료</title>
</head>

<body>
    <div class='popup_container flex'>
        <div class='product-exchange-complete-title-wrap'>
            <div class='check-img-wrap'>
                <img src="{% static 'images/users/mypage/user/check_nohover.svg' %}" alt='check_nohover'>
            </div>
            <div class='product-exchange-complete-main-title'>교환 신청 완료</div>
            <div class='product-exchange-complete-sub-title'>고객님의 교환신청이 완료되었습니다.</div>
        </div>
        <div class='border-line'></div>
        <div class='main-content-wrap'>
            <div class='exchange-product-information-title'>교환 상품 정보</div>
            <div class='exchange-product-receipt-wrap'>
                <div class='exchange-product-receipt-top-section'>
                    <div class='exchange-date-wrap wrap_padding flex'>
                        <span class='exchange-date-title'>주문일시</span>
                        <span class='exchange-date-value'>{{order_date}}</span>
                    </div>
                    <div class='exchange-product-information-wrap wrap_padding'>
                        <div class='farm-information-wrap flex'>
                            <div class='farm-information-title'>Farm</div>
                            <div class='farm-information-value'>{{farm_name}}</div>
                        </div>
                        <div class='exchange-product-information-contents-wrap'>
                            <!-- 무난이 작물 시작-->
                            <div class='exchange-product-information-content-wrap flex'>
                                <div class='exchange-product-information-content-left-section'>
                                    <div class='exchange-product-image'>
                                    </div>
                                </div>
                                <div class='exchange-product-information-content-right-section'>
                                    {% if product_kinds == "ugly" %}
                                    <div class='refund-product-tag'>
                                        <img src="{% static 'images/users/mypage/user/moonan_harvest_tag.svg' %}" alt='moonan_harvest_tag'>
                                    </div>
                                    {% else %}
                                    <div class='refund-product-tag'>
                                        <img src="{% static 'images/users/mypage/user/normal_harvest_tag.svg' %}""" alt='moonan_harvest_tag'>
                                    </div>
                                    {% endif %}
                                    <div class='exchange-product-name'>{{product_title}}</div>
                                    <div class='exchange-product-detail-wrap flex'>
                                        <div class='exchange-product-price'>{{product_price}}원</div>
                                        <div class='exchange-product-quantity'>{{order_detail_quantity}}</div>
                                        <div class='exchange-product-quantity-unit'>(개/박스)</div>
                                        <div class='exchange-product-weight'>{{product_weight}}</div>
                                    </div>
                                    <div class='exchange-product-option'>교환신청</div>
                                </div>
                            </div>
                            <!-- 무난이 작물 끝-->


                        </div>
                    </div>
                </div>
                <div class='drag-bag-product-wrap'>
                    <div class='drag-bag-product-title'>배송 / 회수 정보</div>
                    <div class='drag-bag-product-content-wrap wrap_padding'>
                        <div class='drag-bag-address-wrap flex'>
                            <div class='drag-bag-address-title'>주소지</div>
                            <div class='drag-bag-address-value'>{{refundExchange.rev_address}}</div>
                        </div>
                        <div class='drag-bag-request-wrap flex'>
                            <div class='drag-bag-request-title'>요청사항</div>
                            <div class='drag-bag-request-value'>{{refundExchange.rev_loc_at}}</div>
                        </div>
                        <div class='drag-bag-cost-wrap flex'>
                            <div class='drag-bag-cost-title'>교환 배송비</div>
                            <div class='drag-bag-cost-value'>{{refundExchange.refund_exchange_delivery_fee}}원</div>
                        </div>
                    </div>
                    <div class='return-mypage-btn-wrap flex'>
                        <div class='return-mypage-btn-img-wrap'>
                            <a href="{% url 'core:popup_callback' %}"><img class='return-mypage-btn-img' src="{% static 'images/users/mypage/user/goback_mypage_nohover.svg' %}" alt='goback_mypage_nohover'></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script defer>
        const return_btn = document.querySelector('.return-mypage-btn-wrap');
        const return_img = document.querySelector('.return-mypage-btn-img');

        const switchCheckImgHoverIn = function (e) {
            return_img.setAttribute('src', "{% static 'images/users/mypage/user/goback_mypage_hover.svg' %}")
        }

        const switchCheckImgHoverOut = function (e) {
            return_img.setAttribute('src', "{% static 'images/users/mypage/user/goback_mypage_nohover.svg' %}")
        }



        return_btn.addEventListener('mouseover', switchCheckImgHoverIn)
        return_btn.addEventListener('mouseleave', switchCheckImgHoverOut)
    </script>
</body>

</html>

templates/users/mypage/user/shipping_info_popup.html
{% extends 'users/mypage/user/popup_base.html' %}
{% load static %}
{% block popup_title %}상품 배송 정보 확인{% endblock %}
{% block popup_content %}


<section id="order-list-section">
    <h1 class="f-title">상품 배송 정보 확인</h1>
    <div id="product-info-section" class="flex w-full flex-col  main-content-section">
        <div class="flex justify-center">
            <img src="{{product.main_image.url}}" alt="" class="product-image">
            <div class="flex flex-col justify-between product-info">
                <div class="flex flex-col">
                    <span class="f-content-label">{{product.title}}</span>
                    <span class="f-content-data">{{quantity}}개</span>
                </div>
                <div class="flex items-center deliver-status">
                    <span class="f-desc-label">{{status}}</span>
                </div>
            </div>
        </div>
        <div class="flex justify-between items-center farmer-info">
            <div class="flex items-center">
                <img src="{{farmer.farmer_profile.url}}" alt="" class="farmer-profile">
                <span class="f-desc-label">{{farmer.farm_name}}</span>
            </div>
            <button class="farmer-page-button" onclick="location.href = `{% url 'farmers:farmer_detail' farmer.pk %}`">
                미니홈피 방문하기
            </button>
        </div>
        <div class="receiver-info grid mx-auto">
            <span class="receiver-info-label f-content-label">수령인</span>
            <span class="receiver-info-label f-content-label">전화번호</span>
            <span class="receiver-info-label f-content-label">주소</span>
            {% if gift is True%}
            <span class="receiver-info-label f-content-label">선물 메세지</span>
            {% else %}
            <span class="receiver-info-label f-content-label">받으실 장소</span>
            <span class="receiver-info-label f-content-label">배송지 특이사항</span>
            {% endif %}

            <span class="receiver-info-data f-content-data">{{rev_name}}</span>
            <span class="receiver-info-data f-content-data">{{rev_phone_number}}</span>
            <span class="receiver-info-data f-content-data">{{rev_address}}</span>

            {% if gift is True%}
            <span class="receiver-info-data f-content-data">{{gift_message}}</span>
            {% else %}
            <span class="receiver-info-data f-content-data">{{rev_loc_at}}</span>
            <span class="receiver-info-data f-content-data">{{rev_message}}</span>
            {% endif %}
            
        </div>
    </div>
    <div class="flex justify-between button-group">
        <button class="f-primary-button f-button-confirm" onclick="location.href = `{% url 'core:main' %}`">확인</button>
    </div>
</section>

{% endblock %}